name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to the GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/surveilr/www.surveilr.com/omnibus-rssd-nginx:latest -f support/deploy/omnibus-rssd-nginx.dockerfile .

      # Push the Docker image to the GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/surveilr/www.surveilr.com/omnibus-rssd-nginx:latest
